name: keep-streamlit-alive

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # 10분마다 실행 (UTC)

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.APP_URL }}   # 시크릿에서 URL 주입

    steps:
      # 1. HEAD 요청으로 가볍게 확인 (리다이렉트 및 네트워크 에러 대비)
      - name: HEAD ping with retry
        run: |
          curl -I -L \
               --max-redirs 5 \
               --retry 3 \
               --retry-all-errors \
               --connect-timeout 10 \
               --max-time 30 \
               "$APP_URL"

      # 2. GET 요청으로 실제 페이지 접근 (백업용)
      - name: GET fallback
        run: |
          curl -sL \
               --max-redirs 5 \
               --retry 3 \
               --retry-all-errors \
               --connect-timeout 10 \
               --max-time 45 \
               "$APP_URL" > /dev/null