name: keep-streamlit-alive

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # 10분마다 실행 (UTC)

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.APP_URL }}
    steps:
        - name: Keep Streamlit awake
          run: |
            curl -I \
                --retry 3 \
                --retry-all-errors \
                --connect-timeout 10 \
                --max-time 30 \
                "$APP_URL"
      