name: keep-streamlit-alive
on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # 10분마다 (UTC)

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.APP_URL }}   # ← 여기서 시크릿을 환경변수로 주입
    steps:
      - name: Debug ping
        run: |
            curl -I -v "$APP_URL"